Clean after exe update

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,14 +1,13 @@
 #!/bin/bash
-DEPLOY=.deploy
-CONTROL_DIR=$(realpath $(dirname "$0"))
-if [ ! -e $CONTROL_DIR/$DEPLOY ]; then
-  echo "Deploy dir '$CONTROL_DIR/$DEPLOY' has not been created"
+
+echo "########################################################"
+echo "Checking environment vars:"
+
+if [ x"${WebServerRoot}" == "x" ]; then 
+  echo "Value 'WebServerRoot' is not assigned to a variable"
   exit 1
 fi
-
-cd $CONTROL_DIR/$DEPLOY
-echo "########################################################"
-echo "Running in: $CONTROL_DIR/$DEPLOY"
+echo "WebServerRoot: $WebServerRoot"
 
 if [ x"${WebServerData}" == "x" ]; then 
   echo "Value 'WebServerData' is not assigned to a variable"
@@ -28,21 +27,53 @@ if [ x"${WebServerPictures}" == "x" ]; then
 fi
 echo "WebServerPictures: $WebServerPictures"
 
-if [ x"${WebServerWebtools}" == "x" ]; then 
-  echo "Value 'WebServerWebtools' is not assigned to a variable"
+
+echo "Checking Paths exist:"
+
+if [ ! -d $WebServerRoot ]; then
+  echo "Deploy dir '$WebServerRoot' has not been created"
   exit 1
 fi
-echo "WebServerWebtools: $WebServerWebtools"
+
+echo "WebServerRoot/exec: $WebServerRoot/exec"
+if [ ! -d $WebServerRoot/exec ]; then
+  echo "Deploy dir '$WebServerRoot/exec' has not been created"
+  exit 1
+fi
+
+if [ ! -d $WebServerData ]; then
+  echo "Deploy dir '$WebServerData' does not exist"
+  exit 1
+fi
+
+if [ ! -d $WebServerHome ]; then
+  echo "Deploy dir '$WebServerHome' does not exist"
+  exit 1
+fi
+
+if [ ! -d $WebServerPictures ]; then
+  echo "Deploy dir '$WebServerPictures' does not exist"
+  exit 1
+fi
+
+cd $WebServerRoot
 echo "########################################################"
+echo "Running in: $WebServerRoot"
+
+if [ ! -e $WebServerRoot/goWebApp ]; then
+  echo "Exec file '$WebServerRoot/goWebApp' does not exist"
+  exit 1
+fi
+
+if [ ! -e $WebServerRoot/exec/webtools ]; then
+  echo "Exec file '$WebServerRoot/exec/webtools' does not exist"
+  exit 1
+fi
+
 while true
 do
-  if [ $USER == stuart ]; then
-    echo "Config file:goWebApp.json"
+  echo "Config file:goWebApp.json"
   ./goWebApp config=goWebApp.json -vr
-  else
-    echo "Config file:goWebAppPi.json"
-  ./goWebApp config=goWebAppPi.json -vr
-  fi
   
   RESP=$?
   echo "########################################################"
@@ -56,6 +87,10 @@ do
     exit 1
   fi
   if [ $RESP -eq 1 ]; then
+    echo "Server error"
+    exit 1
+  fi
+  if [ $RESP -eq 127 ]; then
     echo "Server error"
     exit 1
   fi
